# Important python libraries

 - `numpy` (numerics) + `scipy` (scientific functions) 
 - `matplotlib` - plotting
 - `astropy` - convenient operations on data for Data Science  (`pandas` is another alternative) 
 - `scikit-learn` - machine learning
 
We'll meet them very soon during the ML session.

## Hello numpy!

`numpy` is the core of scientific python. It is the most convenient way to organize number-crunching in python.

In [5]:
import numpy

In [6]:
x = numpy.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
x.reshape(5, 2)

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [8]:
x.reshape(2, 5)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [9]:
# slicing has the same logic for lists / strings / tuples / numpy, etc
x[:4]

array([0, 1, 2, 3])

In [10]:
print x[:3]
print x[3:7]
print x[7:]

[0 1 2]
[3 4 5 6]
[7 8 9]


### Vector operations

In [11]:
x = numpy.arange(10 ** 6)
# vector operations do similar task for each element. In this case each element is multiplied by 3 and 12 added.
3 * x + 12.

array([  1.20000000e+01,   1.50000000e+01,   1.80000000e+01, ...,
         3.00000300e+06,   3.00000600e+06,   3.00000900e+06])

In [12]:
# use timing magic to understand this is quite fast
%timeit 3 * x + 12.

100 loops, best of 3: 7.59 ms per loop


In [13]:
Z = numpy.arange(15).reshape(5, 3)
Z

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [14]:
numpy.log(numpy.exp(Z)) # type conversion happened

array([[  0.,   1.,   2.],
       [  3.,   4.,   5.],
       [  6.,   7.,   8.],
       [  9.,  10.,  11.],
       [ 12.,  13.,  14.]])

In [15]:
Z += 4

In [16]:
Z

array([[ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12],
       [13, 14, 15],
       [16, 17, 18]])

In [17]:
Z[::2, :]

array([[ 4,  5,  6],
       [10, 11, 12],
       [16, 17, 18]])

In [18]:
Z[[0, 2, 4], :]

array([[ 4,  5,  6],
       [10, 11, 12],
       [16, 17, 18]])

In [19]:
Z.sum(axis=1)

array([15, 24, 33, 42, 51])

In [20]:
# axes are also zero-numerated
Z.sum(axis=0)

array([50, 55, 60])

In [21]:
Z.max(axis=1)

array([ 6,  9, 12, 15, 18])

In [22]:
Z2 = - Z
Z2 = numpy.sort(Z2, axis=1)
Z2

array([[ -6,  -5,  -4],
       [ -9,  -8,  -7],
       [-12, -11, -10],
       [-15, -14, -13],
       [-18, -17, -16]])

## Indexing with boolean array

In [23]:
x = numpy.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [24]:
x > 3

array([False, False, False, False,  True,  True,  True,  True,  True,  True], dtype=bool)

In [25]:
x[x < 7.4]

array([0, 1, 2, 3, 4, 5, 6, 7])

## Copies

Many operations in numpy don't create copies, but operate with the same memory 

In [26]:
x = numpy.arange(10)
y = x[:5]

print x, y
y[0] = 10
print x, y

[0 1 2 3 4 5 6 7 8 9] [0 1 2 3 4]
[10  1  2  3  4  5  6  7  8  9] [10  1  2  3  4]


this happened because x and y point __to the same place in memory__

In [27]:
x = numpy.arange(10)
y = x[:5].copy()
print x, y
y[0] = 10
print x, y

[0 1 2 3 4 5 6 7 8 9] [0 1 2 3 4]
[0 1 2 3 4 5 6 7 8 9] [10  1  2  3  4]


## Random numbers

module `numpy.random` helps with generating random numbers

In [28]:
# generating 10000 random numbers at once
numpy.random.normal(loc=2, scale=12, size=10000)

array([-23.05765305,   0.59671923,  15.52091888, ...,  -5.47098557,
        15.98049344, -22.3912203 ])

## Sorting

In [29]:
x = numpy.random.random(size=1000)
x = numpy.sort(x)

In [30]:
print x[:10]
print x[-10:]

[ 0.00134819  0.00163771  0.0020615   0.00224523  0.00244322  0.00344626
  0.00810889  0.00927277  0.01207061  0.0125285 ]
[ 0.99457426  0.99529254  0.99558779  0.99694301  0.99706573  0.99725458
  0.997728    0.99911017  0.99911726  0.99997476]


## Arg...

arg-functions allow writing non-trivial operations with a couple of lines

In [31]:
# random.random generates uniform in [0, 1]
random_numbers = numpy.random.random(size=1000)
indices = numpy.argsort(random_numbers)

In [32]:
numpy.alltrue(random_numbers[indices] == numpy.sort(random_numbers))

True

In [33]:
indices[:10]

array([201, 562, 816, 981, 174, 166, 967, 612, 735, 980])

In [34]:
random_numbers.min(), random_numbers.max()

(0.0015944886740317799, 0.99861811006419265)

In [35]:
random_numbers.argmax(), random_numbers[random_numbers.argmax()]

(457, 0.99861811006419265)

In [36]:
random_numbers.argmin(), random_numbers[random_numbers.argmin()]

(201, 0.0015944886740317799)

## Exercise

In [37]:
# 0. import numpy
import numpy

In [38]:
# 1. sample 1000 elements from normal distribution 
rand0 = numpy.random.normal(0,1,1000)

In [39]:
# 2. leave only positive numbers (from previous exercise)
rand1 = rand0[rand0 > 0]

In [40]:
# 3. count number of left numbers, their minimum, maximum, mean and variance.
print rand1.size, rand1.min(), rand1.max(), rand1.mean(), rand1.std()

479 0.00531594510185 2.95490039458 0.787296764387 0.588693418362


## References:
* `numpy` documentation: https://docs.scipy.org/doc/numpy/reference/
    * almost any question about `numpy` is already answered on stackoverflow
* [From python to numpy: a beautiful book about numpy](https://github.com/rougier/from-python-to-numpy)
* Data manipulation with `numpy`: tips and tricks [part1](http://arogozhnikov.github.io/2015/09/29/NumpyTipsAndTricks1.html), [part2](http://arogozhnikov.github.io/2015/09/30/NumpyTipsAndTricks2.html)
