# Important python libraries

 - `numpy` (numerics) + `scipy` (scientific functions) 
 - `matplotlib` - plotting
 - `astropy` - convenient operations on data for Data Science  (`pandas` is another alternative) 
 - `scikit-learn` - machine learning
 
We'll meet them very soon during the ML session.

## Hello numpy!

`numpy` is the core of scientific python. It is the most convenient way to organize number-crunching in python.

In [12]:
import numpy

In [13]:
x = numpy.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [14]:
x.reshape(5, 2)

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [15]:
x.reshape(2, 5)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [16]:
# slicing has the same logic for lists / strings / tuples / numpy, etc
x[:4]

array([0, 1, 2, 3])

In [17]:
print x[:3]
print x[3:7]
print x[7:]

[0 1 2]
[3 4 5 6]
[7 8 9]


### Vector operations

In [18]:
x = numpy.arange(10 ** 6)
# vector operations do similar task for each element. In this case each element is multiplied by 3 and 12 added.
3 * x + 12.

array([  1.20000000e+01,   1.50000000e+01,   1.80000000e+01, ...,
         3.00000300e+06,   3.00000600e+06,   3.00000900e+06])

In [19]:
# use timing magic to understand this is quite fast
%timeit 3 * x + 12.

100 loops, best of 3: 3.47 ms per loop


In [20]:
Z = numpy.arange(15).reshape(5, 3)
Z

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [21]:
numpy.log(numpy.exp(Z)) # type conversion happened

array([[  0.,   1.,   2.],
       [  3.,   4.,   5.],
       [  6.,   7.,   8.],
       [  9.,  10.,  11.],
       [ 12.,  13.,  14.]])

In [22]:
Z += 4

In [23]:
Z

array([[ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12],
       [13, 14, 15],
       [16, 17, 18]])

In [24]:
Z[::2, :]

array([[ 4,  5,  6],
       [10, 11, 12],
       [16, 17, 18]])

In [25]:
Z[[0, 2, 4], :]

array([[ 4,  5,  6],
       [10, 11, 12],
       [16, 17, 18]])

In [26]:
Z.sum(axis=1)

array([15, 24, 33, 42, 51])

In [27]:
# axes are also zero-numerated
Z.sum(axis=0)

array([50, 55, 60])

In [28]:
Z.max(axis=1)

array([ 6,  9, 12, 15, 18])

In [29]:
Z2 = - Z
Z2 = numpy.sort(Z2, axis=1)
Z2

array([[ -6,  -5,  -4],
       [ -9,  -8,  -7],
       [-12, -11, -10],
       [-15, -14, -13],
       [-18, -17, -16]])

## Indexing with boolean array

In [30]:
x = numpy.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [31]:
x > 3

array([False, False, False, False,  True,  True,  True,  True,  True,  True], dtype=bool)

In [32]:
x[x < 7.4]

array([0, 1, 2, 3, 4, 5, 6, 7])

## Copies

Many operations in numpy don't create copies, but operate with the same memory 

In [33]:
x = numpy.arange(10)
y = x[:5]

print x, y
y[0] = 10
print x, y

[0 1 2 3 4 5 6 7 8 9] [0 1 2 3 4]
[10  1  2  3  4  5  6  7  8  9] [10  1  2  3  4]


this happened because x and y point __to the same place in memory__

In [34]:
x = numpy.arange(10)
y = x[:5].copy()
print x, y
y[0] = 10
print x, y

[0 1 2 3 4 5 6 7 8 9] [0 1 2 3 4]
[0 1 2 3 4 5 6 7 8 9] [10  1  2  3  4]


## Random numbers

module `numpy.random` helps with generating random numbers

In [35]:
# generating 10000 random numbers at once
numpy.random.normal(loc=2, scale=12, size=10000)

array([  3.71295099,  33.35489164,   9.36881288, ...,  13.46463172,
         7.38411473,  28.31113302])

## Sorting

In [36]:
x = numpy.random.random(size=1000)
x = numpy.sort(x)

In [37]:
print x[:10]
print x[-10:]

[ 0.00122569  0.00292035  0.00389644  0.00436615  0.00447912  0.00540812
  0.00658721  0.00659308  0.00665564  0.00833606]
[ 0.99215326  0.99276469  0.99329952  0.99452275  0.99518514  0.99550127
  0.99610824  0.99635971  0.99780777  0.99825653]


## Arg...

arg-functions allow writing non-trivial operations with a couple of lines

In [38]:
# random.random generates uniform in [0, 1]
random_numbers = numpy.random.random(size=1000)
indices = numpy.argsort(random_numbers)

In [39]:
numpy.alltrue(random_numbers[indices] == numpy.sort(random_numbers))

True

In [40]:
indices[:10]

array([ 77, 407, 165,  41, 592, 802, 476, 228, 986, 362])

In [41]:
random_numbers.min(), random_numbers.max()

(0.00061639047206230035, 0.99986746925324843)

In [42]:
random_numbers.argmax(), random_numbers[random_numbers.argmax()]

(345, 0.99986746925324843)

In [43]:
random_numbers.argmin(), random_numbers[random_numbers.argmin()]

(77, 0.00061639047206230035)

## Exercise

In [44]:
# 0. import numpy
import numpy

In [46]:
# 1. sample 1000 elements from normal distribution 
rand0 = numpy.random.normal(0,1,1000)
print rand0

[ -1.31150004e+00   7.60201487e-01  -9.72294163e-01  -1.70777884e-01
  -4.83758210e-01   1.06080646e+00  -1.26064293e+00   1.37726204e+00
   2.54344775e-01  -1.11481755e+00   1.27120438e+00   6.07719565e-01
  -1.57524881e+00  -1.24203443e+00   2.65096136e-01   2.68143022e-01
   4.72212851e-01   1.09265650e+00   9.80216579e-01   3.46552116e-01
  -1.44924755e+00   1.06468518e+00   2.28814122e+00  -3.31051422e-01
   1.91015585e-01   1.43123390e+00  -1.21516865e+00  -7.26128024e-01
   2.73373041e-01   1.48231841e+00  -1.11015489e+00   1.15314562e+00
  -7.45029251e-01  -1.93340470e-01   1.89526995e+00  -4.37719290e-01
  -2.17309801e-01   2.02026299e+00  -5.47397319e-01  -8.95545660e-01
   1.75564754e+00   9.14667462e-01  -9.80269885e-02   1.19035554e+00
   8.10373759e-01   6.44192768e-01   1.29912223e-02  -3.80896000e-01
  -1.04391988e+00  -1.64088756e+00   3.02978729e-01  -6.79039028e-01
  -9.72768037e-02   2.17327597e+00  -8.54487493e-03  -3.62421179e-01
  -3.58728591e-01  -6.76168693e-01

In [48]:
# 2. leave only positive numbers (from previous exercise)
rand1 = rand0[rand0 > 0]

In [51]:
# 3. count number of left numbers, their minimum, maximum, mean and variance.
print rand1.size, rand1.min(), rand1.max(), rand1.mean(), rand1.std()

521 6.49537169159e-05 3.67671506154 0.822868179639 0.620413895103


## References:
* `numpy` documentation: https://docs.scipy.org/doc/numpy/reference/
    * almost any question about `numpy` is already answered on stackoverflow
* [From python to numpy: a beautiful book about numpy](https://github.com/rougier/from-python-to-numpy)
* Data manipulation with `numpy`: tips and tricks [part1](http://arogozhnikov.github.io/2015/09/29/NumpyTipsAndTricks1.html), [part2](http://arogozhnikov.github.io/2015/09/30/NumpyTipsAndTricks2.html)
